version: '3.7'

services:
    dbt:
        image: "ghcr.io/dbt-labs/dbt-postgres:1.3.1"
        volumes:
            - "./:/usr/app/dbt"
            - "./profiles.yml:/root/.dbt/profiles.yml"
        # command: "debug"
        # command: "run --var='{\"integration_id\": \"dc24aa96-7a1f-4abb-b1cc-992848ad5971\", \"workspace_id\": \"1203531897608619\"}'"
        command: "run --vars='{\"table_prefix\":\"_aeaecfe7\",\"timestamp\":\"1674902623.235171\",\"integration_id\":\"aeaecfe7-53cb-4afe-a9e3-d0e801ff0f66\"}'"
        networks:
            default:
            db-bridge:
                aliases: 
                    - db
networks:
    db-bridge:
        name: db-bridge
        driver: bridge
